sonar.projectKey=myproject
sonar.sources=src
sonar.inclusions=src/**/*.ts,src/**/*.tsx,src/**/*.js,src/**/*.jsx,src/**/*.html,src/**/*.scss,src/**/*.css
sonar.exclusions=**/node_modules/**,**/dist/**,*.spec.ts,**/*.spec.ts
sonar.language=ts
sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.sourceEncoding=UTF-8
sonar.token=squ_45cb6fedc34beb287a6b795ac072f5be3e3ca642